name: docker-ci
on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "app/**"
      - "requirements.txt"
      - ".github/workflows/docker-ci.yml"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build (sin push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: fastapi-observability-demo:ci
