name: docker-ci
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: fastapi-observability-demo:ci
on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker-ci.yml'
  pull_request:
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch:
